from typing import Protocol

from type_alias import CNF, Literal, Variable

class DPLLSolverObserver(Protocol):
    def on_recursive_call( self, depth: int, cnf: CNF ) -> None: ...
    def on_unit_propagation( self, literal: Literal ) -> None: ...
    def on_pure_literal( self, literal: Literal ) -> None: ...
    def on_decision( self, variable: Variable ) -> None: ...
    def on_backtrack( self, variable: Variable ) -> None: ...