"""
observer.py
"""
from typing import Protocol
from type_alias import CNF, Variable

class DPSolverObserver(Protocol):
    def on_start(self, cnf: CNF) -> None: ...
    def on_iteration(self, cnf: CNF) -> None: ...
    def on_variable_eliminated(self, variable: Variable) -> None: ...
    def on_resolution(self) -> None: ...
    def on_finish(self, result: bool, cnf: CNF) -> None: ...