from typing import Protocol

from type_alias import CNF, Literal


class CDCLSolverObserver(Protocol):
    def on_recursive_call( self, level: int, cnf: CNF) -> None: ...
    def on_decision(self, literal: Literal, level: int) -> None: ...
    def on_unit_propagation(self, literal: Literal) -> None: ...
    def on_conflict(self, clause: frozenset[int]) -> None: ...
    def on_clause_learned(self, clause: frozenset[int]) -> None: ...
    def on_backjump(self, from_level: int, to_level: int) -> None: ...
    def on_clause_database_size(self, size: int) -> None: ...
    def on_restart(self) -> None: ...
